# -*- coding: utf-8 -*-
"""
maya-mcp 설치 스크립트. Maya 스크립트 에디터(Python 탭)에서 한 번만 실행합니다.

    import sys; sys.path.append(r"C:\\path\\to\\maya-mcp")
    import install_maya; install_maya.install()

세 가지를 설치합니다.
  1. userSetup.py  — Maya 를 켜면 브릿지가 자동으로 대기 상태가 됩니다.
  2. 셸프 버튼     — 'MCP' 셸프에 원버튼 시작/중지 토글.
  3. sys.path 등록 — 매번 sys.path.append 를 칠 필요가 없어집니다.

제거하려면 같은 방식으로 실행한 뒤 uninstall() 을 부르세요.
"""

import io
import os
import re

import maya.cmds as cmds
import maya.mel as mel

REPO_DIR = os.path.dirname(os.path.abspath(__file__))
SHELF_NAME = "MCP"
BUTTON_LABEL = "MCP"

_MARK_BEGIN = "# >>> maya-mcp begin >>>"
_MARK_END = "# <<< maya-mcp end <<<"

# 생성되는 블록은 ASCII 만 씁니다. Windows 기본 인코딩(cp949)으로 기록돼도
# Maya 의 Python 3 가 UTF-8 로 읽을 때 깨지지 않게 하기 위해서입니다.
_BLOCK = '''%s
# Generated by install_maya.py. Safe to delete this block by hand.
import sys as _sys
_MCP_DIR = r"%s"
if _MCP_DIR not in _sys.path:
    _sys.path.append(_MCP_DIR)

def _mcp_autostart():
    try:
        import maya_mcp_bridge
        maya_mcp_bridge.start()
    except Exception:
        import traceback
        traceback.print_exc()

import maya.utils as _mu
_mu.executeDeferred(_mcp_autostart)
%s
'''


def _scripts_dir():
    """<userAppDir>/scripts — 모든 Maya 버전이 공유하는 스크립트 폴더."""
    path = os.path.join(cmds.internalVar(userAppDir=True), "scripts")
    if not os.path.isdir(path):
        os.makedirs(path)
    return path


def _user_setup_path():
    return os.path.join(_scripts_dir(), "userSetup.py")


def _strip_block(text):
    pattern = re.compile(re.escape(_MARK_BEGIN) + r".*?" + re.escape(_MARK_END) + r"\n?",
                         re.DOTALL)
    return pattern.sub("", text)


# ------------------------------------------------------------ 자동 시작

def _read_text(path):
    """기존 userSetup.py 는 UTF-8 이 아닐 수 있습니다. 깨지지 않게 읽습니다."""
    with io.open(path, "rb") as fh:
        raw = fh.read()
    for enc in ("utf-8", "cp949", "latin-1"):
        try:
            return raw.decode(enc)
        except UnicodeDecodeError:
            continue
    return raw.decode("utf-8", "replace")


def install_autostart():
    path = _user_setup_path()
    existing = _read_text(path) if os.path.exists(path) else ""

    body = _strip_block(existing).rstrip()
    block = _BLOCK % (_MARK_BEGIN, REPO_DIR, _MARK_END)
    new = (body + "\n\n" + block) if body else block

    # 반드시 UTF-8 로 기록합니다. Maya 의 Python 3 가 소스를 UTF-8 로 읽습니다.
    with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(new)
    return path


def uninstall_autostart():
    path = _user_setup_path()
    if not os.path.exists(path):
        return None
    text = _read_text(path)
    stripped = _strip_block(text).strip()
    if stripped:
        with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(stripped + "\n")
    else:
        os.remove(path)          # 우리 블록밖에 없었으면 파일째 제거
    return path


# ------------------------------------------------------------ 셸프 버튼

# 여기서 importlib.reload 를 하면 안 됩니다. 리로드는 모듈 전역(_server)을
# 초기화하므로 이미 떠 있는 서버를 stop() 할 수 없게 되고, 포트가 물린 채로
# start() 가 실패합니다. 코드를 갱신하려면 Maya 를 재시작하세요.
_BUTTON_CMD = '''import sys
if r"%s" not in sys.path:
    sys.path.append(r"%s")
import maya_mcp_bridge
maya_mcp_bridge.toggle()
''' % (REPO_DIR, REPO_DIR)


def _remove_existing_buttons(shelf):
    for child in (cmds.shelfLayout(shelf, q=True, childArray=True) or []):
        try:
            if cmds.shelfButton(child, q=True, label=True) == BUTTON_LABEL:
                cmds.deleteUI(child)
        except Exception:
            pass


def install_shelf():
    top = mel.eval("$_tmp = $gShelfTopLevel")
    if not cmds.shelfLayout(SHELF_NAME, exists=True):
        mel.eval('addNewShelfTab("%s")' % SHELF_NAME)
    _remove_existing_buttons(SHELF_NAME)

    cmds.setParent(top + "|" + SHELF_NAME)
    btn = cmds.shelfButton(
        label=BUTTON_LABEL,
        annotation="maya-mcp 브릿지 시작/중지 토글",
        image="commandButton.png",
        imageOverlayLabel="MCP",
        overlayLabelColor=(0.2, 0.9, 0.7),
        sourceType="python",
        command=_BUTTON_CMD,
        parent=SHELF_NAME,
    )
    mel.eval("saveAllShelves $gShelfTopLevel;")
    return btn


def uninstall_shelf():
    if cmds.shelfLayout(SHELF_NAME, exists=True):
        _remove_existing_buttons(SHELF_NAME)
        mel.eval("saveAllShelves $gShelfTopLevel;")
        return True
    return False


# ------------------------------------------------------------ 진입점

def install(autostart=True, shelf=True):
    print("[maya-mcp] 설치 위치: %s" % REPO_DIR)
    if autostart:
        print("[maya-mcp] 자동 시작 등록: %s" % install_autostart())
    if shelf:
        install_shelf()
        print("[maya-mcp] 셸프 버튼 추가: '%s' 셸프 > %s" % (SHELF_NAME, BUTTON_LABEL))
    print("[maya-mcp] 완료. Maya 를 재시작하면 자동으로 대기 상태가 됩니다.")
    print("[maya-mcp] 지금 바로 쓰려면 셸프의 MCP 버튼을 누르세요.")


def uninstall():
    p = uninstall_autostart()
    print("[maya-mcp] 자동 시작 해제: %s" % (p or "설정 없음"))
    print("[maya-mcp] 셸프 버튼 제거: %s" % ("완료" if uninstall_shelf() else "없음"))
    print("[maya-mcp] 제거 완료. Maya 재시작 후 반영됩니다.")


if __name__ == "__main__":
    install()
